<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>PSYC489K, Session 1: The Basics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="regression_r_script_week1_COMPLETE_files/libs/clipboard/clipboard.min.js"></script>
<script src="regression_r_script_week1_COMPLETE_files/libs/quarto-html/quarto.js"></script>
<script src="regression_r_script_week1_COMPLETE_files/libs/quarto-html/popper.min.js"></script>
<script src="regression_r_script_week1_COMPLETE_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="regression_r_script_week1_COMPLETE_files/libs/quarto-html/anchor.min.js"></script>
<link href="regression_r_script_week1_COMPLETE_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="regression_r_script_week1_COMPLETE_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="regression_r_script_week1_COMPLETE_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="regression_r_script_week1_COMPLETE_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="regression_r_script_week1_COMPLETE_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PSYC489K, Session 1: The Basics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This week’s session is about catching everyone up to speed on R and regression. This is a long script, but it’s for your benefit to look through the solutions and ask questions on what you don’t understand.</p>
<section id="r-recap" class="level1">
<h1>R Recap</h1>
<section id="data-types" class="level2">
<h2 class="anchored" data-anchor-id="data-types">Data Types</h2>
<p>In this section, we’re going to practice working with and creating data of different data types.</p>
<section id="numericinteger-data" class="level3">
<h3 class="anchored" data-anchor-id="numericinteger-data">Numeric/Integer Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a vector of integers with the numbers 0 to 100</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>numbers <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>numbers2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) <span class="co"># another option</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>numbers3 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">100</span>, <span class="at">by =</span> <span class="dv">1</span>) <span class="co"># another option</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># create a vector of the number 1 repeated 1000 times. Check the length of this to verify it is correct.</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>lottaones <span class="ot">=</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">1000</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(lottaones)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the mean of the following vector</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>vec <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">10</span>), <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">5</span>, .<span class="dv">4</span>), <span class="dv">31</span><span class="sc">:</span><span class="dv">45</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.52174</code></pre>
</div>
</div>
<p>What would be the class of the following vector: c(1L, 2L, 3.5L)</p>
</section>
<section id="character-data" class="level3">
<h3 class="anchored" data-anchor-id="character-data">Character Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a vector with 3 letters and 1 sentence, each as individual elements. What is the length of this vector? </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>letters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"a"</span>,<span class="st">"B"</span>,<span class="st">"I like dogs."</span>,<span class="st">"D"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(letters)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector called cat with the word cat in it and a vector called dog with the word dog in it. Compare cat &gt; dog. What happens and why? </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cats <span class="ot">&lt;-</span> <span class="st">"cat"</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>dogs <span class="ot">&lt;-</span> <span class="st">"dog"</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>cats <span class="sc">&gt;</span> dogs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># this statement is FALSE because it's based on the first letter of the word (the CONTENTS of the object, not the object name itself)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="logical-data" class="level3">
<h3 class="anchored" data-anchor-id="logical-data">Logical Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a condition that evaluates as true</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="st">"dogs"</span> <span class="sc">==</span> <span class="st">"dogs"</span> <span class="co"># true because they're the same character data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a condtiion that evaluates as false</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="cn">TRUE</span> <span class="sc">==</span> <span class="cn">FALSE</span> <span class="co"># false because they're different logical values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a condition with an OR statement that evaluates to TRUE.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>numbs <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(numbs) <span class="sc">&lt;</span> <span class="dv">50</span> <span class="sc">|</span> <span class="fu">max</span>(numbs) <span class="sc">&lt;</span> <span class="dv">50</span> <span class="co"># true because at least one of the two - the minimum - is less than 50</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a condition with an AND statement that evaluates to FALSE.</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(numbs) <span class="sc">&lt;</span> <span class="dv">50</span> <span class="sc">&amp;</span> <span class="fu">max</span>(numbs) <span class="sc">&lt;</span> <span class="dv">50</span> <span class="co"># false because only the minimum value is less than 50</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
</section>
<section id="factor-data" class="level3">
<h3 class="anchored" data-anchor-id="factor-data">Factor Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"small"</span>,<span class="st">"medium"</span>, <span class="st">"large"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># turn the above vector into a factor with ordered levels.</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> <span class="fu">factor</span>(sizes, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"small"</span>,<span class="st">"medium"</span>,<span class="st">"large"</span>), <span class="at">ordered=</span><span class="cn">TRUE</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>countries <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"US"</span>,<span class="st">"Sweden"</span>,<span class="st">"China"</span>,<span class="st">"Egypt"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co"># turn the above vector into a factor with unordered levels </span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>countries <span class="ot">=</span> <span class="fu">factor</span>(countries, <span class="at">levels =</span> <span class="fu">unique</span>(countries), <span class="at">ordered =</span> <span class="cn">FALSE</span>) <span class="co"># unique(countries) will pull all unique values in the countries vector so we're avoiding repeats. This works well here because there's no order to the levels of the factor.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="general" class="level3">
<h3 class="anchored" data-anchor-id="general">General</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the class of the below vector</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>messy <span class="ot">&lt;-</span> <span class="fu">c</span>(1L, <span class="cn">TRUE</span>, <span class="st">"0"</span>, <span class="dv">125</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(messy) <span class="co"># it is character because there is one character value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>messy1 <span class="ot">&lt;-</span> <span class="fu">c</span>(1L, <span class="cn">TRUE</span>, <span class="dv">125</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(messy1) <span class="co"># it is numeric because there is one numeric value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>messy2 <span class="ot">&lt;-</span> <span class="fu">c</span>(1L, <span class="cn">TRUE</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(messy2) <span class="co"># it is integer because there is one integer value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>messy3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(messy3) <span class="co"># it is logical because there is one logical value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "logical"</code></pre>
</div>
</div>
</section>
</section>
<section id="data-structures" class="level2">
<h2 class="anchored" data-anchor-id="data-structures">Data Structures</h2>
<section id="vectors" class="level3">
<h3 class="anchored" data-anchor-id="vectors">Vectors</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create vector with the INTEGERS 1 through 100 </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>int_vec <span class="ot">=</span> <span class="fu">c</span>(1L<span class="sc">:</span>100L)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(int_vec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># divde this vector by 2 and check the resulting data type</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(int_vec<span class="sc">/</span><span class="dv">2</span>) <span class="co"># this is numeric because there are decimal values. (Every odd number divided by 2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
</div>
</section>
<section id="matrices" class="level3">
<h3 class="anchored" data-anchor-id="matrices">Matrices</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a 2x3 matrix with the numbers 1 through 6 in it going from left to right (1, 2, 3 in row 1, 4, 5, and 6 in row 2)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>); test <span class="co"># we need byrow = TRUE here because it will fill columns then rows by default</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># multiply all elements in the matrix by 2 in a single operation</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">*</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]
[1,]    2    4    6
[2,]    8   10   12</code></pre>
</div>
</div>
</section>
<section id="data-frames" class="level3">
<h3 class="anchored" data-anchor-id="data-frames">Data Frames</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a data frame with three columnns named numbers, numbers_squared, and numbers_doubled. The first column should be the numbers 1 through 10, the second and third columns should be those numbers squared and doubled, respectively. </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">numbers =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">numbers_squared =</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">numbers_doubled =</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)<span class="sc">*</span><span class="dv">2</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   numbers numbers_squared numbers_doubled
1        1               1               2
2        2               4               4
3        3               9               6
4        4              16               8
5        5              25              10
6        6              36              12
7        7              49              14
8        8              64              16
9        9              81              18
10      10             100              20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a fourth column in your data frame called ratio and make it the first column divided by the second column. </span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>ratio <span class="ot">=</span> df<span class="sc">$</span>numbers<span class="sc">/</span>df<span class="sc">$</span>numbers_squared</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>ratio2 <span class="ot">=</span> df[,<span class="dv">1</span>]<span class="sc">/</span>df[,<span class="dv">2</span>] <span class="co"># a second way to do it</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>ratio3 <span class="ot">=</span> df[,<span class="st">"numbers"</span>]<span class="sc">/</span>df[,<span class="st">"numbers_squared"</span>] <span class="co"># a third way to do it</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># all of the above are equally good solutions to indexing the data frame</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>df <span class="co"># verify these do the same thing</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   numbers numbers_squared numbers_doubled     ratio    ratio2    ratio3
1        1               1               2 1.0000000 1.0000000 1.0000000
2        2               4               4 0.5000000 0.5000000 0.5000000
3        3               9               6 0.3333333 0.3333333 0.3333333
4        4              16               8 0.2500000 0.2500000 0.2500000
5        5              25              10 0.2000000 0.2000000 0.2000000
6        6              36              12 0.1666667 0.1666667 0.1666667
7        7              49              14 0.1428571 0.1428571 0.1428571
8        8              64              16 0.1250000 0.1250000 0.1250000
9        9              81              18 0.1111111 0.1111111 0.1111111
10      10             100              20 0.1000000 0.1000000 0.1000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(df<span class="sc">$</span>ratio <span class="sc">==</span> df<span class="sc">$</span>ratio2) <span class="sc">&amp;</span> <span class="fu">all</span>(df<span class="sc">$</span>ratio2 <span class="sc">==</span> df<span class="sc">$</span>ratio3)  <span class="co"># verify these are equivalent by using the all() command, which checks whether all values are equal (i.e., all are true)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
</section>
<section id="loops" class="level2">
<h2 class="anchored" data-anchor-id="loops">Loops</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loop through the COLUMNS of the data frame above and calculate the standard deviation of each row</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>sd_vec <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">ncol</span>(df)) <span class="co"># make this the same length of the number of columns of the data frame</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(df)){ <span class="co"># this loops through the number of columns of the data frame, so i will be set to 1 through 6, incremented by 1</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  sd_vec[i] <span class="ot">&lt;-</span> <span class="fu">sd</span>(df[,i]) <span class="co"># this will assign the standard deviation of the ith column of the data frame to the ith element of the standard deviation vector. </span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>sd_vec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3.0276504 34.1735765  6.0553007  0.2772649  0.2772649  0.2772649</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a for loop that prints the expression "HELLO WORLD!" the number of rows of the data frame above. </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df)){</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">"HELLO WORLD!"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>} <span class="co"># this will loop through the code 10 times and print hello world each time because i = 1, ..., 10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"
[1] "HELLO WORLD!"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create an empty results vector the number of rows of the data frame above and fill it with the numbers of the first column doubled. Compare it to the third column in your data frame.</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>res <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">nrow</span>(df))</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df)){</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  res[i] <span class="ot">=</span> df[i,<span class="dv">1</span>]<span class="sc">*</span><span class="dv">2</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>res <span class="sc">==</span> df[,<span class="dv">3</span>] <span class="co"># it worked! Note, this is less efficient than simply multiplying the values by 2 like we did when creating the data frame</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE</code></pre>
</div>
</div>
</section>
<section id="working-with-data" class="level2">
<h2 class="anchored" data-anchor-id="working-with-data">Working with Data</h2>
<p>It is critical for us to be able to read in and manipulate data. Please follow the comments in the following code chunk to show your data wrangling skills.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the dataset "airquality" from R using the data() command. </span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(airquality)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># describe this dataset with a single line of code. </span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(airquality) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Ozone           Solar.R           Wind             Temp      
 Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
 1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
 Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
 Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
 3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
 Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
 NA's   :37       NA's   :7                                       
     Month            Day      
 Min.   :5.000   Min.   : 1.0  
 1st Qu.:6.000   1st Qu.: 8.0  
 Median :7.000   Median :16.0  
 Mean   :6.993   Mean   :15.8  
 3rd Qu.:8.000   3rd Qu.:23.0  
 Max.   :9.000   Max.   :31.0  
                               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot two numeric variables of your choice to show you can do it</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(airquality<span class="sc">$</span>Solar.R, airquality<span class="sc">$</span>Wind)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_r_script_week1_COMPLETE_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the craving.csv dataset in preparation for the second half of this file</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>craving <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/PSYC489K-SU25/Datasets/craving.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="debugging" class="level2">
<h2 class="anchored" data-anchor-id="debugging">Debugging</h2>
<p>Below are lines of code, each with one error. Please fix them so this document renders!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>numbers <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>) <span class="co"># issue: two equals signs instead of one</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>halved <span class="ot">=</span> numbers<span class="sc">/</span><span class="dv">2</span> <span class="co"># issue: numbers was capitalized here and not above</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>char <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"a"</span>,<span class="st">"b"</span>,<span class="st">"c"</span>,<span class="st">"D"</span>) <span class="co"># issue: missing quotes around c</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(char) <span class="co"># issue: p in print was capitalized</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "a" "b" "c" "D"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">numbers =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">letters =</span> <span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"C"</span>)) <span class="co"># issue: used is.data.frame() instead of data.frame() to create data frame</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(df) <span class="sc">==</span> <span class="fu">length</span>(df) <span class="co"># this should be true # issue: it was missing a second equals sign</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
</section>
<section id="regression-recap" class="level1">
<h1>Regression Recap</h1>
<p>The example for today comes from a study on mental health and substance abuse (Witkiewitz &amp; Bowen, 2010). The authors collected data from 168 clients of a public service agency providing treatment for alcohol and substance use disorders. Clients were measured on depression and cravings for alcohol at the beginning and end of a two-month treatment plan. They wanted to determine whether baseline levels of depression significantly predicted alcohol cravings at the end of the program. The variables in the dataset are:</p>
<ul>
<li>BDI0: Scores on the Beck Depression Inventory at the start of therapy. (Scale: 0-3). This is the <strong>predictor</strong>.</li>
<li>CRAVE2: Score on the Penn Alcohol Craving Scale (PACS) two months after therapy. (Scale: 0-6). This is the <strong>outcome</strong>.</li>
<li>CRAVE0: Score on the PACS at the start of therapy. (Scale: 0-6)</li>
<li>TREATHRS: Hours of therapy administered during treatment program.</li>
</ul>
<section id="reading-in-the-data" class="level2">
<h2 class="anchored" data-anchor-id="reading-in-the-data">Reading in the data</h2>
<p>Below is the start to reading in the dataset craving.csv. Complete it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>craving <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/PSYC489K-SU25/Datasets/craving.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-the-required-packages" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-required-packages">Loading the required packages</h2>
<p>Please load in the ggplot2 and jtools packages using the appropriate syntax.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="descriptives" class="level2">
<h2 class="anchored" data-anchor-id="descriptives">Descriptives</h2>
<p>The first thing we want to do is explore our data. This starts with obtaining the descriptives (e.g., mean, range) for reach of the variables in our dataset. Do this using a function in one line of code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(craving)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      bdi0           crave0          crave2         treathrs    
 Min.   :0.000   Min.   :0.800   Min.   :0.000   Min.   :10.00  
 1st Qu.:1.000   1st Qu.:2.400   1st Qu.:1.400   1st Qu.:26.00  
 Median :1.190   Median :3.000   Median :2.000   Median :31.00  
 Mean   :1.196   Mean   :2.943   Mean   :2.114   Mean   :30.68  
 3rd Qu.:1.380   3rd Qu.:3.600   3rd Qu.:2.600   3rd Qu.:35.00  
 Max.   :2.140   Max.   :5.600   Max.   :5.800   Max.   :48.00  </code></pre>
</div>
</div>
</section>
<section id="creating-a-plot" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-plot">Creating a plot</h2>
<p>Please create a scatterplot in ggplot2 for the predictor and the outcome appropriately placed on the <em>x</em>- and <em>y</em>-axes, respectively. ggplot has a very particular syntax, so I will generally provide the bones here and have you plug in your variables. Color the points by the number of treatment hours a client received.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span> craving, <span class="fu">aes</span>(<span class="at">x=</span>bdi0, <span class="at">y =</span> crave2 , <span class="at">color =</span> treathrs)) <span class="sc">+</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  jtools<span class="sc">::</span><span class="fu">theme_apa</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_r_script_week1_COMPLETE_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="checking-the-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-assumptions">Checking the assumptions</h2>
<section id="normality-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="normality-of-residuals">Normality of residuals</h3>
<p>This is established by creating a Q-Q plot (should be a straight line of any slope) or a histogram of the residuals (should look normal). Let’s create both below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>bdi_model <span class="ot">=</span> <span class="fu">lm</span>(crave2 <span class="sc">~</span> bdi0, <span class="at">data =</span>craving)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(bdi_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_r_script_week1_COMPLETE_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">resid</span>(bdi_model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_r_script_week1_COMPLETE_files/figure-html/unnamed-chunk-16-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What can we say about the assumption of normality?</p>
<p>The assumption seems reasonable. The histogram appears to be normal in shape and the qq-plot showed a relatively straight line. There don’t seem to be gross departures from normality here.</p>
</section>
<section id="heteroskedasticity-and-linearity" class="level3">
<h3 class="anchored" data-anchor-id="heteroskedasticity-and-linearity">Heteroskedasticity and linearity</h3>
<p>These are determined from the scatterplot above. What can we say about these assumptions?</p>
<p><strong>Heteroskedasticity</strong>: Does not seem to be present based on the plot. There are no obvious funnel shapes or change in the variance of X across Y.</p>
<p><strong>Linearity</strong>: Linearity seems to be a reasonable assumption given the plot. There are no curves or flattening off points.</p>
</section>
</section>
<section id="writing-out-the-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="writing-out-the-hypotheses">Writing out the hypotheses</h2>
<p>What might we expect about the relationship between depression and alcohol cravings? (Hint: Think whether this is a one-tailed or two-tailed hypothesis.) Write the null and alternative hypotheses below (in terms of the parameters):</p>
<p>H0: B1 &lt;= 0 (i.e., the population effect of depression on alcohol cravings is negative or zero).</p>
<p>H1: B1 &gt; 0 (i.e., depression will have a positive effect on alcohol cravings)</p>
</section>
<section id="fitting-the-model-to-the-data" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model-to-the-data">Fitting the model to the data</h2>
<p>Please fit a simple linear regression model to the data and interpret each coefficient in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bdi_model) <span class="co"># using the model object from earlier</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = crave2 ~ bdi0, data = craving)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2433 -0.6103 -0.0590  0.4792  3.3252 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.9605     0.2800   3.431  0.00076 ***
bdi0          0.9645     0.2262   4.264 3.36e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9326 on 166 degrees of freedom
Multiple R-squared:  0.09872,   Adjusted R-squared:  0.09329 
F-statistic: 18.18 on 1 and 166 DF,  p-value: 3.359e-05</code></pre>
</div>
</div>
<p>B0: The intercept was 0.961 (t = 3.423, p &lt; .001). People with a depression score of zero are expected to have an alcohol craving of 0.961.</p>
<p>B1: The effect of depression at baseline on subsequent alcohol cravings was significant, b1 = 0.965, t = 4.26, p &lt; .001. People’s cravings were expected to increase by 0.965 for each one-unit increase in depressive symptoms.</p>
</section>
<section id="expanding-the-model" class="level2">
<h2 class="anchored" data-anchor-id="expanding-the-model">Expanding the model</h2>
<p>Although the above is a start, it’s likely not a well-specified model. We have two other variables in the dataset. What can we do with them? Rerun the model and interpret each coefficient.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we're going to run a multiple regression controlling for cravings at baseline and treatment hours and see if anything changes. </span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>mult_bdi_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(crave2 <span class="sc">~</span> crave0 <span class="sc">+</span> bdi0 <span class="sc">+</span> treathrs, <span class="at">data =</span> craving)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mult_bdi_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = crave2 ~ crave0 + bdi0 + treathrs, data = craving)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.0877 -0.5661 -0.0426  0.4467  3.5329 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.35459    0.44849   3.020 0.002930 ** 
crave0       0.22546    0.07718   2.921 0.003977 ** 
bdi0         0.78126    0.22548   3.465 0.000677 ***
treathrs    -0.02732    0.01052  -2.598 0.010219 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9005 on 164 degrees of freedom
Multiple R-squared:  0.1698,    Adjusted R-squared:  0.1546 
F-statistic: 11.18 on 3 and 164 DF,  p-value: 1.024e-06</code></pre>
</div>
</div>
<p>B0: Those with no cravings or depressive symptoms at baseline with 0 treatment hours were expected to have an alcohol craving of 1.355 at the end of the treatment plan, b0 = 1.355, t = 3.02, p &lt; .001.</p>
<p>B1: The effect of baseline cravings on subsequent cravings was significant after controlling for baseline depression and treatment hours, b1 = 0.225, t = 2.921, p = .003. People’s cravings were expected to increase by 0.225 for each additional unit of baseline cravings.</p>
<p>B2: The effect of baseline depression on subsequent cravings was significant after controlling for baseline cravings and treatment hours, b2 = 0.781, t = 3.465, p = .001. People’s cravings were expected to increase by .781 for each additional unit of depressive symptomatology.</p>
<p>B3: The effect of treatment hours on subsequent cravings was significant after controlling for baseline depression and baseline cravings, b3 = -0.027, t = -2.598, p = .010. People’s craving were expected to decrease by 0.027 units for each additional hour of therapy they received.</p>
</section>
<section id="interpreting-the-results" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-results">Interpreting the results</h2>
<p>What can we say given our exploration?</p>
<p>It seems like depressive symptoms are a huge contributing factor to alcohol abuse. They do not act in isolation, however, as a predisposition to cravings is also impactful and therapy does help reduce cravings over time.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>