<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>PSYC489K, Session 4: Simple Moderation Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="moderation_script_sync_session_4_COMPLETE_files/libs/clipboard/clipboard.min.js"></script>
<script src="moderation_script_sync_session_4_COMPLETE_files/libs/quarto-html/quarto.js"></script>
<script src="moderation_script_sync_session_4_COMPLETE_files/libs/quarto-html/popper.min.js"></script>
<script src="moderation_script_sync_session_4_COMPLETE_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="moderation_script_sync_session_4_COMPLETE_files/libs/quarto-html/anchor.min.js"></script>
<link href="moderation_script_sync_session_4_COMPLETE_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="moderation_script_sync_session_4_COMPLETE_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="moderation_script_sync_session_4_COMPLETE_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="moderation_script_sync_session_4_COMPLETE_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="moderation_script_sync_session_4_COMPLETE_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PSYC489K, Session 4: Simple Moderation Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="moderation" class="level1">
<h1>Moderation</h1>
<p>Moderation analysis allows us to uncover the “when” and “for whom” qualifying a causal effect. In other words, it can tell us the boundary conditions of an effect—when it is positive versus negative, present versus not, or stronger versus weaker. Most, if not all effects, are moderated. It is common for a relationship to vary as a function of gender, race, presence of a psychological disorder, or level of some continuous factor (e.g., age or mg of a drug). As we’ll see, the testing of moderation is actually quite simple. (It’s just multiple regression.) It is the interpretation of moderated (aka “interaction”) effects that can become challenging.</p>
<p><strong>Equation</strong></p>
<p>As mentioned previously, a simple moderation model is just a simple multiple regression equation with one new parameter (to us):</p>
<p><em>Y</em> = dy + b1<em>X</em> + b2<em>W</em> + b3<em>X</em>*<em>W</em></p>
<p>Note: We represent moderators with <em>W</em> to avoid confusion with mediators/mediation. The only new thing here is the product of <em>X</em> and <em>W</em>, which carries the interaction effect. All we need to do is test the weight for this effect, b3, to determine whether moderation is present. This can be done with typical regression procedures. (i.e., We don’t need to use bootstrapping, Monte Carlo, or anything else fancy.)</p>
<section id="load-required-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-required-packages">Load required packages</h2>
<p>You should load the <strong>jtools</strong> and <strong>ggplot2</strong> packages. Be sure to also load PROCESS. (The code below will let my computer know where the process_v5.R file is stored so it can manually retrieve and run the file while rendering. It will generate an error otherwise.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># remember to load PROCESS and route it to the correct location</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"~/PSYC489K-SU25/process_v5.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
 
PROCESS is now ready for use.
Copyright 2013-2025 by Andrew F. Hayes ALL RIGHTS RESERVED
Workshop schedule at haskayne.ucalgary.ca/CCRAM 
Information about PROCESS available at processmacro.org/faq.html </code></pre>
</div>
</div>
</section>
<section id="read-in-and-summarize-the-data" class="level2">
<h2 class="anchored" data-anchor-id="read-in-and-summarize-the-data">Read in and summarize the data</h2>
<p>Our data today come from a study on Palestinian children experiencing traumatic events during the Al-Aqsa Intifada on the Gaza strip in 2006 (Peltonen et al., 2010). These data have been generated to produce identical results to the original study. A total of 113 children were measured on a variety of constructs including:</p>
<ul>
<li><p><strong>age:</strong> The age of the child in years. (Range: 10-14)</p></li>
<li><p><strong>depress:</strong> Self-reported depression levels, higher scores = more depression. (Range: 1-28)</p></li>
<li><p><strong>trauma:</strong> Number of traumatic events experienced (e.g., house exploding, witnessing a death), higher scores = more trauma. (Range: 0-18)</p></li>
<li><p><strong>lonely:</strong> Self-reported loneliness. Higher scores = more loneliness. (Range: 1-5)</p></li>
<li><p><strong>ptsd:</strong> Self-reported PTSD symptoms. Higher scores = more symptoms. (Range: 0-54)</p></li>
</ul>
<p>Our hypothesis is that loneliness the relationship between PTSD and depression. Specifically, X = ptsd, W = lonely, and Y = depression.</p>
<p>Read in and summarize the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read data into data frame</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>child_trauma <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/PSYC489K-SU25/Datasets/trauma.csv"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># now summarize the data</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(child_trauma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age             ptsd           lonely          trauma      
 Min.   :10.00   Min.   : 0.00   Min.   :1.000   Min.   : 0.000  
 1st Qu.:11.00   1st Qu.:20.00   1st Qu.:1.430   1st Qu.: 5.000  
 Median :12.00   Median :30.00   Median :2.140   Median : 7.000  
 Mean   :11.59   Mean   :28.21   Mean   :2.232   Mean   : 7.796  
 3rd Qu.:12.00   3rd Qu.:36.00   3rd Qu.:2.860   3rd Qu.:10.000  
 Max.   :14.00   Max.   :54.00   Max.   :5.000   Max.   :18.000  
    depress     
 Min.   : 1.00  
 1st Qu.: 6.00  
 Median :10.00  
 Mean   :10.39  
 3rd Qu.:14.00  
 Max.   :28.00  </code></pre>
</div>
</div>
</section>
<section id="fitting-the-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model">Fitting the Model</h2>
<p>First, we will fit the model to the data and test whether the interaction is significant. Then, we will follow up this inferential test by probing the interaction effect to better understand the dynamics of the relationship.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(depress<span class="sc">~</span>ptsd<span class="sc">*</span>lonely, <span class="at">data =</span> child_trauma); <span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = depress ~ ptsd * lonely, data = child_trauma)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.078  -4.385  -1.255   3.646  17.320 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 11.69665    3.62141   3.230  0.00164 **
ptsd        -0.26219    0.12190  -2.151  0.03369 * 
lonely      -0.66152    1.46234  -0.452  0.65190   
ptsd:lonely  0.12040    0.04956   2.430  0.01675 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.891 on 109 degrees of freedom
Multiple R-squared:  0.1712,    Adjusted R-squared:  0.1484 
F-statistic: 7.507 on 3 and 109 DF,  p-value: 0.0001296</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(depress<span class="sc">~</span>ptsd <span class="sc">+</span> lonely <span class="sc">+</span> ptsd<span class="sc">:</span>lonely, <span class="at">data =</span>child_trauma); <span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = depress ~ ptsd + lonely + ptsd:lonely, data = child_trauma)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.078  -4.385  -1.255   3.646  17.320 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 11.69665    3.62141   3.230  0.00164 **
ptsd        -0.26219    0.12190  -2.151  0.03369 * 
lonely      -0.66152    1.46234  -0.452  0.65190   
ptsd:lonely  0.12040    0.04956   2.430  0.01675 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.891 on 109 degrees of freedom
Multiple R-squared:  0.1712,    Adjusted R-squared:  0.1484 
F-statistic: 7.507 on 3 and 109 DF,  p-value: 0.0001296</code></pre>
</div>
</div>
<p><strong>Is the interaction effect significant? What can we say about this relationship?</strong></p>
<p>b1: Depression is expected to decrease by .26 units when loneliness is 0 and ptsd increases by one unit. This effect is significant, b1 = -0.26, t = -2.15, p = .03.</p>
<p>b2: Depression is expected to decrease by .66 units when ptsd is 0 and loneliness increases by one unit. This effect is not significant, b2 = -0.66, t = -0.45, p = .65.</p>
<p>b3: The effect of ptsd on depression is expected to increase by 0.12 units for each one-unit increase in loneliness (and vice versa). This effect is significant, b3 = 0.12, t = 2.43, p = .02.</p>
<p>The interaction effect is significant. Thus, we can conclude that loneliness moderates the relationship between ptsd and depression, such that the more lonely one is, the more ptsd symptoms lead to depressive symptoms (and vice versa).</p>
</section>
<section id="the-simple-slopes-procedure" class="level2">
<h2 class="anchored" data-anchor-id="the-simple-slopes-procedure">The Simple Slopes Procedure</h2>
<p>We will first probe the model with the simple slopes procedure. This allows us to test the conditional effect of the predictor at different values of the moderator. It also allows us to create a nice, simple visualization. To keep things simple, we’re just going to probe the interaction at the mean +/- one SD of the moderator.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## doing it manually</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># first, obtain critical values of X - the mean +/- one SD</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>xneg1sd <span class="ot">&lt;-</span> <span class="fu">mean</span>(child_trauma<span class="sc">$</span>ptsd)<span class="sc">-</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>ptsd)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>mx <span class="ot">&lt;-</span> <span class="fu">mean</span>(child_trauma<span class="sc">$</span>ptsd)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>xplus1sd <span class="ot">&lt;-</span> <span class="fu">mean</span>(child_trauma<span class="sc">$</span>ptsd)<span class="sc">+</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>ptsd)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># now, obtain critical values of M - the mean +/- one SD</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>wneg1sd <span class="ot">&lt;-</span> <span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely)<span class="sc">-</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>lonely)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>mw <span class="ot">&lt;-</span> <span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>wplus1sd <span class="ot">&lt;-</span> <span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely)<span class="sc">+</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>lonely)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># assemble into data frame</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ptsd =</span> <span class="fu">rep</span>(<span class="fu">c</span>(xneg1sd, mx, xplus1sd),<span class="dv">3</span>), <span class="at">lonely =</span> <span class="fu">c</span>(<span class="fu">rep</span>(wneg1sd, <span class="dv">3</span>),<span class="fu">rep</span>(mw,<span class="dv">3</span>),<span class="fu">rep</span>(wplus1sd,<span class="dv">3</span>)))</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># predict values of Y</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>ypred <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, temp)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># assemble into final data frame for plotting</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>probe_ss_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>temp<span class="sc">$</span>ptsd, <span class="at">y =</span> ypred, <span class="at">w =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Low"</span>, <span class="dv">3</span>),<span class="fu">rep</span>(<span class="st">"Average"</span>,<span class="dv">3</span>),<span class="fu">rep</span>(<span class="st">"High"</span>,<span class="dv">3</span>)))</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="do">## doing it in PROCESS...much easier</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co"># plot = 1 will create a simple slopes by default. It will also generate a dataset you can use to create your own plot</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co"># moments = 1 will generate values of the moderator at the mean +/- one SD, which is what we want</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">data =</span> child_trauma, <span class="at">x =</span> <span class="st">"ptsd"</span>, <span class="at">w =</span> <span class="st">"lonely"</span>, <span class="at">y =</span> <span class="st">"depress"</span>, <span class="at">model =</span> <span class="dv">1</span>, <span class="at">moments =</span> <span class="dv">1</span>, <span class="at">plot =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
                
  Model: 1      
      Y: depress
      X: ptsd   
      W: lonely 

Sample size: 113


*********************************************************************** 
Outcome Variable: depress

Model Summary: 
          R      R-sq       MSE         F       df1       df2         p
     0.4138    0.1712   34.7079    7.5074    3.0000  109.0000    0.0001

Model: 
             coeff        se         t         p      LLCI      ULCI
constant   11.6966    3.6214    3.2299    0.0016    4.5191   18.8742
ptsd       -0.2622    0.1219   -2.1509    0.0337   -0.5038   -0.0206
lonely     -0.6615    1.4623   -0.4524    0.6519   -3.5598    2.2368
int_1       0.1204    0.0496    2.4295    0.0168    0.0222    0.2186

Product terms key:
int_1  :  ptsd  x  lonely      

Test(s) of highest order unconditional interaction(s):
      R2-chng         F       df1       df2         p
X*W    0.0449    5.9025    1.0000  109.0000    0.0168
----------
Focal predictor: ptsd (X)
      Moderator: lonely (W)

Conditional effects of the focal predictor at values of the moderator(s):
     lonely    effect        se         t         p      LLCI      ULCI
     1.3432   -0.1005    0.0653   -1.5384    0.1269   -0.2299    0.0290
     2.2324    0.0066    0.0461    0.1427    0.8868   -0.0848    0.0980
     3.1216    0.1136    0.0622    1.8261    0.0706   -0.0097    0.2370

Data for visualizing the conditional effect of the focal predictor:
       ptsd    lonely   depress
    16.1275    1.3432    9.1877
    28.2124    1.3432    7.9735
    40.2972    1.3432    6.7593
    16.1275    2.2324   10.3260
    28.2124    2.2324   10.4055
    40.2972    2.2324   10.4851
    16.1275    3.1216   11.4643
    28.2124    3.1216   12.8375
    40.2972    3.1216   14.2108</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

W values in conditional tables are the mean and +/- SD from the mean.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use the PROCESS output to create the dataset</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>x_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="fl">16.1275</span>, <span class="fl">28.2124</span>, <span class="fl">40.2972</span>), <span class="dv">3</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>w_values <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Low"</span>, <span class="dv">3</span>), <span class="fu">rep</span>(<span class="st">"Average"</span>, <span class="dv">3</span>), <span class="fu">rep</span>(<span class="st">"High"</span>, <span class="dv">3</span>)), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Average"</span>, <span class="st">"High"</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>y_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">9.1877</span>, <span class="fl">7.9735</span>, <span class="fl">6.7593</span>, <span class="fl">10.3260</span>, <span class="fl">10.4055</span>, <span class="fl">10.4851</span>, <span class="fl">11.4643</span>, <span class="fl">12.8375</span>, <span class="fl">14.2108</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x_values, <span class="at">y =</span> y_values, <span class="at">w =</span> w_values)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="do">## creating the visualization</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>probe_ss_dat) <span class="sc">+</span> <span class="co"># lets ggplot know the data frame we're working with</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y,<span class="at">color=</span>w)) <span class="sc">+</span> <span class="co"># create lines</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y =</span>y, <span class="at">color=</span>w)) <span class="sc">+</span> <span class="co"># add dots at end of lines</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="co"># this makes it neat and tidy</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="co"># start theme code, remove grid</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(), <span class="co"># remove grid</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">color=</span><span class="st">"black"</span>), <span class="co"># remove background</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span>.<span class="dv">5</span>), <span class="co"># center x axis title</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span>.<span class="dv">5</span>), <span class="co"># center y axis title</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(), <span class="co"># add axis lines</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">color=</span><span class="st">"black"</span>)) <span class="sc">+</span> <span class="co"># end theme code</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color=</span><span class="fu">guide_legend</span>(<span class="at">title=</span><span class="st">"Loneliness (W)"</span>)) <span class="sc">+</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">"#F8766D"</span>,<span class="st">"#00BA38"</span>,<span class="st">"#619CFF"</span>)) <span class="sc">+</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"PTSD Symptoms"</span>,<span class="at">y=</span><span class="st">"Depression"</span>) <span class="co"># relabel axes</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-johnson-neyman-technique" class="level2">
<h2 class="anchored" data-anchor-id="the-johnson-neyman-technique">The Johnson-Neyman Technique</h2>
<p>The JN technique (aka floodlight analysis) tells us at what value(s) of a continuous moderator the effect of the focal predictor on the outcome becomes significant. We can use the quadratic formula to derive these points, but PROCESS thankfully does this for us. All you need to do is add <strong>jn=1</strong> to the PROCESS command.</p>
<p>*Note: PROCESS will only show you valid solutions. (i.e., No imaginary numbers and only values that fit in the observed range of the moderator.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## doing it in PROCESS - we're going to keep it easy</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># jn = 1 will produce the J-N results</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">process</span>(<span class="at">data=</span>child_trauma, <span class="at">x =</span> <span class="st">"ptsd"</span>, <span class="at">w =</span> <span class="st">"lonely"</span>, <span class="at">y =</span> <span class="st">"depress"</span>, <span class="at">model =</span> <span class="dv">1</span>, <span class="at">plot =</span> <span class="dv">1</span>, <span class="at">moments =</span> <span class="dv">1</span>, <span class="at">jn =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
                
  Model: 1      
      Y: depress
      X: ptsd   
      W: lonely 

Sample size: 113


*********************************************************************** 
Outcome Variable: depress

Model Summary: 
          R      R-sq       MSE         F       df1       df2         p
     0.4138    0.1712   34.7079    7.5074    3.0000  109.0000    0.0001

Model: 
             coeff        se         t         p      LLCI      ULCI
constant   11.6966    3.6214    3.2299    0.0016    4.5191   18.8742
ptsd       -0.2622    0.1219   -2.1509    0.0337   -0.5038   -0.0206
lonely     -0.6615    1.4623   -0.4524    0.6519   -3.5598    2.2368
int_1       0.1204    0.0496    2.4295    0.0168    0.0222    0.2186

Product terms key:
int_1  :  ptsd  x  lonely      

Test(s) of highest order unconditional interaction(s):
      R2-chng         F       df1       df2         p
X*W    0.0449    5.9025    1.0000  109.0000    0.0168
----------
Focal predictor: ptsd (X)
      Moderator: lonely (W)

Conditional effects of the focal predictor at values of the moderator(s):
     lonely    effect        se         t         p      LLCI      ULCI
     1.3432   -0.1005    0.0653   -1.5384    0.1269   -0.2299    0.0290
     2.2324    0.0066    0.0461    0.1427    0.8868   -0.0848    0.0980
     3.1216    0.1136    0.0622    1.8261    0.0706   -0.0097    0.2370

Moderator value(s) defining Johnson-Neyman significance region(s):
      Value   % below   % above
     3.3130   89.3805   10.6195

Conditional effect of focal predictor at values of the moderator:
     lonely    effect        se         t         p      LLCI      ULCI
     1.0000   -0.1418    0.0783   -1.8111    0.0729   -0.2970    0.0134
     1.2000   -0.1177    0.0705   -1.6693    0.0979   -0.2575    0.0221
     1.4000   -0.0936    0.0633   -1.4781    0.1423   -0.2192    0.0319
     1.6000   -0.0696    0.0570   -1.2203    0.2250   -0.1825    0.0434
     1.8000   -0.0455    0.0518   -0.8781    0.3818   -0.1481    0.0572
     2.0000   -0.0214    0.0481   -0.4451    0.6571   -0.1167    0.0739
     2.2000    0.0027    0.0462    0.0580    0.9539   -0.0889    0.0943
     2.4000    0.0268    0.0465    0.5759    0.5659   -0.0653    0.1189
     2.6000    0.0508    0.0488    1.0426    0.2994   -0.0458    0.1475
     2.8000    0.0749    0.0528    1.4176    0.1592   -0.0298    0.1797
     3.0000    0.0990    0.0583    1.6967    0.0926   -0.0166    0.2146
     3.2000    0.1231    0.0649    1.8963    0.0606   -0.0056    0.2517
     3.3130    0.1367    0.0690    1.9820    0.0500   -0.0000    0.2734
     3.4000    0.1472    0.0722    2.0374    0.0440    0.0040    0.2903
     3.6000    0.1712    0.0801    2.1374    0.0348    0.0125    0.3300
     3.8000    0.1953    0.0884    2.2093    0.0292    0.0201    0.3705
     4.0000    0.2194    0.0970    2.2618    0.0257    0.0271    0.4116
     4.2000    0.2435    0.1058    2.3006    0.0233    0.0337    0.4532
     4.4000    0.2676    0.1148    2.3299    0.0217    0.0400    0.4951
     4.6000    0.2916    0.1240    2.3523    0.0205    0.0459    0.5373
     4.8000    0.3157    0.1332    2.3697    0.0196    0.0517    0.5798
     5.0000    0.3398    0.1426    2.3834    0.0189    0.0572    0.6224</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Data for visualizing the conditional effect of the focal predictor:
       ptsd    lonely   depress
    16.1275    1.3432    9.1877
    28.2124    1.3432    7.9735
    40.2972    1.3432    6.7593
    16.1275    2.2324   10.3260
    28.2124    2.2324   10.4055
    40.2972    2.2324   10.4851
    16.1275    3.1216   11.4643
    28.2124    3.1216   12.8375
    40.2972    3.1216   14.2108</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

W values in conditional tables are the mean and +/- SD from the mean.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># JN via process</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># save = 2 will store the results of your JN analysis so we can create a plot</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>jnres <span class="ot">&lt;-</span> <span class="fu">process</span>(<span class="at">data =</span> child_trauma, <span class="at">x =</span> <span class="st">"ptsd"</span>,<span class="at">w =</span> <span class="st">"lonely"</span>, <span class="at">y =</span> <span class="st">"depress"</span>, <span class="at">model =</span> <span class="dv">1</span>, <span class="at">plot =</span><span class="dv">1</span>, <span class="at">jn =</span><span class="dv">1</span>,<span class="at">moments =</span><span class="dv">1</span>, <span class="at">save =</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
**************** PROCESS Procedure for R Version 5.0 ****************** 
 
           Written by Andrew F. Hayes, Ph.D.  www.afhayes.com              
   Documentation available in Hayes (2022). www.guilford.com/p/hayes3   
 
*********************************************************************** 
                
  Model: 1      
      Y: depress
      X: ptsd   
      W: lonely 

Sample size: 113


*********************************************************************** 
Outcome Variable: depress

Model Summary: 
          R      R-sq       MSE         F       df1       df2         p
     0.4138    0.1712   34.7079    7.5074    3.0000  109.0000    0.0001

Model: 
             coeff        se         t         p      LLCI      ULCI
constant   11.6966    3.6214    3.2299    0.0016    4.5191   18.8742
ptsd       -0.2622    0.1219   -2.1509    0.0337   -0.5038   -0.0206
lonely     -0.6615    1.4623   -0.4524    0.6519   -3.5598    2.2368
int_1       0.1204    0.0496    2.4295    0.0168    0.0222    0.2186

Product terms key:
int_1  :  ptsd  x  lonely      

Test(s) of highest order unconditional interaction(s):
      R2-chng         F       df1       df2         p
X*W    0.0449    5.9025    1.0000  109.0000    0.0168
----------
Focal predictor: ptsd (X)
      Moderator: lonely (W)

Conditional effects of the focal predictor at values of the moderator(s):
     lonely    effect        se         t         p      LLCI      ULCI
     1.3432   -0.1005    0.0653   -1.5384    0.1269   -0.2299    0.0290
     2.2324    0.0066    0.0461    0.1427    0.8868   -0.0848    0.0980
     3.1216    0.1136    0.0622    1.8261    0.0706   -0.0097    0.2370

Moderator value(s) defining Johnson-Neyman significance region(s):
      Value   % below   % above
     3.3130   89.3805   10.6195

Conditional effect of focal predictor at values of the moderator:
     lonely    effect        se         t         p      LLCI      ULCI
     1.0000   -0.1418    0.0783   -1.8111    0.0729   -0.2970    0.0134
     1.2000   -0.1177    0.0705   -1.6693    0.0979   -0.2575    0.0221
     1.4000   -0.0936    0.0633   -1.4781    0.1423   -0.2192    0.0319
     1.6000   -0.0696    0.0570   -1.2203    0.2250   -0.1825    0.0434
     1.8000   -0.0455    0.0518   -0.8781    0.3818   -0.1481    0.0572
     2.0000   -0.0214    0.0481   -0.4451    0.6571   -0.1167    0.0739
     2.2000    0.0027    0.0462    0.0580    0.9539   -0.0889    0.0943
     2.4000    0.0268    0.0465    0.5759    0.5659   -0.0653    0.1189
     2.6000    0.0508    0.0488    1.0426    0.2994   -0.0458    0.1475
     2.8000    0.0749    0.0528    1.4176    0.1592   -0.0298    0.1797
     3.0000    0.0990    0.0583    1.6967    0.0926   -0.0166    0.2146
     3.2000    0.1231    0.0649    1.8963    0.0606   -0.0056    0.2517
     3.3130    0.1367    0.0690    1.9820    0.0500   -0.0000    0.2734
     3.4000    0.1472    0.0722    2.0374    0.0440    0.0040    0.2903
     3.6000    0.1712    0.0801    2.1374    0.0348    0.0125    0.3300
     3.8000    0.1953    0.0884    2.2093    0.0292    0.0201    0.3705
     4.0000    0.2194    0.0970    2.2618    0.0257    0.0271    0.4116
     4.2000    0.2435    0.1058    2.3006    0.0233    0.0337    0.4532
     4.4000    0.2676    0.1148    2.3299    0.0217    0.0400    0.4951
     4.6000    0.2916    0.1240    2.3523    0.0205    0.0459    0.5373
     4.8000    0.3157    0.1332    2.3697    0.0196    0.0517    0.5798
     5.0000    0.3398    0.1426    2.3834    0.0189    0.0572    0.6224</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Data for visualizing the conditional effect of the focal predictor:
       ptsd    lonely   depress
    16.1275    1.3432    9.1877
    28.2124    1.3432    7.9735
    40.2972    1.3432    6.7593
    16.1275    2.2324   10.3260
    28.2124    2.2324   10.4055
    40.2972    2.2324   10.4851
    16.1275    3.1216   11.4643
    28.2124    3.1216   12.8375
    40.2972    3.1216   14.2108</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
******************** ANALYSIS NOTES AND ERRORS ************************ 

Level of confidence for all confidence intervals in output: 95

W values in conditional tables are the mean and +/- SD from the mean.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># this line will interact with the saved object above to help you create the plot below</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>perfx <span class="ot">&lt;-</span> jnres[<span class="dv">12</span><span class="sc">:</span><span class="dv">33</span>,<span class="dv">1</span>];effex <span class="ot">&lt;-</span> jnres[<span class="dv">12</span><span class="sc">:</span><span class="dv">33</span>,<span class="dv">2</span>];llciex <span class="ot">&lt;-</span> jnres[<span class="dv">12</span><span class="sc">:</span><span class="dv">33</span>,<span class="dv">6</span>];ulciex <span class="ot">&lt;-</span> jnres[<span class="dv">12</span><span class="sc">:</span><span class="dv">33</span>,<span class="dv">7</span>]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># J-N plot</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x=</span>perfx,<span class="at">y=</span>effex,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">lwd=</span><span class="dv">3</span>,<span class="at">col=</span><span class="st">"black"</span>,<span class="at">ylab=</span><span class="st">"Conditional Effect of PTSD"</span>,<span class="at">xlab=</span><span class="st">"Loneliness (W)"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(perfx,llciex,<span class="at">lwd=</span><span class="fl">1.75</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(perfx,ulciex,<span class="at">lwd=</span><span class="fl">1.75</span>,<span class="at">lty=</span><span class="dv">2</span>,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>,<span class="at">untf=</span><span class="cn">FALSE</span>,<span class="at">lty=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">1</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fl">3.313</span>,<span class="at">untf=</span><span class="cn">FALSE</span>,<span class="at">lty=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">1</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">3.5</span>,.<span class="dv">1</span>,<span class="st">"3.31"</span>,<span class="at">cex=</span>.<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The region of significance for this problem is values of loneliness that are greater than or equal to 3.31. The conditional effect of PTSD on depression is not significant at any values lower than this (in the range of the data). This applies to 10.62% of the data. The visualization is just there to show this region. (It’s hard to interpret so don’t worry about it too much.)</p>
</section>
<section id="a-complex-visualization" class="level2">
<h2 class="anchored" data-anchor-id="a-complex-visualization">A Complex Visualization</h2>
<p>This is a complex visualization that combines the simple slopes and JN techniques. It is not going to be expected you can recreate this, because it involves some pretty complex visualization code. But I will show this code to you multiple times in different situations so you become more familiar with it!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">### new graph, combination of scatterplot, simple slopes, and J-N</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the moderation model</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>simpmod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>child_trauma,depress<span class="sc">~</span>ptsd<span class="sc">*</span>lonely)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># grab the coefficients from the model</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fu">coef</span>(simpmod)[<span class="dv">1</span>];b1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(simpmod)[<span class="dv">2</span>];b2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(simpmod)[<span class="dv">3</span>];b3 <span class="ot">&lt;-</span> <span class="fu">coef</span>(simpmod)[<span class="dv">4</span>]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co"># simple slope/intercept for "low" loneliness (minus one SD)</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>sintlow <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b2<span class="sc">*</span>(<span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely)<span class="sc">-</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>lonely));sslolow <span class="ot">&lt;-</span> b1 <span class="sc">+</span> b3<span class="sc">*</span>(<span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely)<span class="sc">-</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>lonely))</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># simple slope/intercept for "medium" loenliness (average)</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>sintmed <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b2<span class="sc">*</span>(<span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely));sslomed <span class="ot">&lt;-</span> b1 <span class="sc">+</span> b3<span class="sc">*</span>(<span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely))</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># simple slope/intercept for "high" loneliness (plus one SD)</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>sinthigh <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b2<span class="sc">*</span>(<span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely)<span class="sc">+</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>lonely));sslohigh <span class="ot">&lt;-</span> b1 <span class="sc">+</span> b3<span class="sc">*</span>(<span class="fu">mean</span>(child_trauma<span class="sc">$</span>lonely)<span class="sc">+</span><span class="fu">sd</span>(child_trauma<span class="sc">$</span>lonely))</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># simple slope/intercept for the region of significance</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>sintsig1 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b2<span class="sc">*</span>(<span class="fl">3.313</span>);sslosig1 <span class="ot">&lt;-</span> b1 <span class="sc">+</span> b3<span class="sc">*</span>(<span class="fl">3.313</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="co"># find observations that are in the loneliness ROS</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>child_trauma<span class="sc">$</span>modinROS <span class="ot">=</span> <span class="fu">as.numeric</span>(child_trauma<span class="sc">$</span>lonely <span class="sc">&gt;=</span> <span class="fl">3.313</span>)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a><span class="co"># new visual with all the bells and whistles</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>child_trauma,<span class="fu">aes</span>(<span class="at">y=</span>depress,<span class="at">x=</span>ptsd,<span class="at">color=</span><span class="fu">as.factor</span>(modinROS))) <span class="sc">+</span> <span class="co"># add points and color by factor</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>(<span class="at">data=</span>child_trauma, <span class="fu">aes</span>(<span class="at">y=</span>depress,<span class="at">x=</span>ptsd),<span class="at">outside=</span><span class="cn">TRUE</span>,<span class="at">sides=</span><span class="st">"tr"</span>, <span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span> <span class="co"># allows for rug plot</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span> <span class="co"># allows for rug plot</span></span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span>sslolow,<span class="at">intercept=</span>sintlow,<span class="at">color=</span><span class="st">"#031D38"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># slope at low levels</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span>sslomed,<span class="at">intercept=</span>sintmed,<span class="at">color=</span><span class="st">"#346E9D"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># slope at medium levels</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span>sslohigh,<span class="at">intercept=</span>sinthigh,<span class="at">color=</span><span class="st">"#55AEF3"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># slope at high levels</span></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope=</span>sslosig1,<span class="at">intercept=</span>sintsig1,<span class="at">color=</span><span class="st">"black"</span>,<span class="at">linetype=</span><span class="st">"dotted"</span>, <span class="at">size =</span><span class="dv">1</span>) <span class="sc">+</span> <span class="co"># add region 1</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name=</span><span class="st">"Loneliness Value (W)"</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Not in ROS"</span>,<span class="st">"ROS"</span>), <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red2"</span>,<span class="st">"green4"</span>)) <span class="sc">+</span> </span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult=</span>.<span class="dv">005</span>)) <span class="sc">+</span></span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult=</span>.<span class="dv">005</span>)) <span class="sc">+</span> </span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(), <span class="co"># remove grid</span></span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(), <span class="co"># remove grid</span></span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">color=</span><span class="st">"black"</span>), <span class="co"># remove background</span></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span>.<span class="dv">5</span>), <span class="co"># center x axis title</span></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">hjust=</span>.<span class="dv">5</span>), <span class="co"># center y axis title</span></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(),</span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">color=</span><span class="st">"black"</span>)) <span class="sc">+</span> <span class="co"># add axis lines, end theme adjustments</span></span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"PTSD Symptoms"</span>,<span class="at">y=</span><span class="st">"Depression"</span>) <span class="sc">+</span> <span class="co"># relabel axes</span></span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="at">geom=</span><span class="st">"text"</span>,<span class="at">size=</span><span class="dv">4</span>, <span class="at">x=</span><span class="dv">26</span>,<span class="at">y=</span><span class="dv">25</span>,<span class="at">label=</span><span class="st">"10.62% of data in region of significance"</span>) <span class="co"># add in ROS info</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
i Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="moderation_script_sync_session_4_COMPLETE_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this graph, we can see that most of the region of significance (i.e., high values of loneliness) applies to persons who scored high on PTSD and depression. There is nothing unusual we see with the simple slopes on the plot of the data (with regard to assumption violations), so all in all this seems like a fine model. (We can interpret it like we have to this point.)</p>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p><em>Tie everything together. What did we learn?</em></p>
<p>It seems like loneliness moderates the relationship between PTSD and depression. As loneliness increases, the effect of PTSD on depression increases. Further, it appears that a decrease in loneliness leads to a negative effect of PTSD on depression. In other words, social support is a buffer against many of the negative effects of PTSD for young boys who have experienced traumatic events.</p>
<p>End of script</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>